### ISSUE TITLE
Iconos

### ISSUE THREAD

**Issue by soyjulius** [orzalaga/orzalaga#1]
![twitter](https://user-images.githubusercontent.com/2185794/152667931-243d365d-ce46-4f72-ae25-605ac0cc1214.svg)

**Comment by soyjulius** [comment]
![facebook](https://user-images.githubusercontent.com/2185794/152667984-3c99fd9b-c53d-4be4-9b72-cde99b67e7d0.svg)

**Comment by soyjulius** [comment]
![instagram-svgrepo-com](https://user-images.githubusercontent.com/2185794/152667993-e2b9da41-0b1b-4387-acb6-b80910f303c6.svg)

**Comment by soyjulius** [comment]
![google-maps-svgrepo-com](https://user-images.githubusercontent.com/2185794/152668092-7e93d0eb-423e-4060-b62b-3b1aaa0215af.svg)

**Comment by soyjulius** [comment]
![camera-svgrepo-com](https://user-images.githubusercontent.com/2185794/152668162-6ac45887-abd2-4e5d-b575-9aa390248399.svg)

**Comment by soyjulius** [comment]
![strava-svgrepo-com](https://user-images.githubusercontent.com/2185794/152668171-78ebf7d0-6fb5-484f-b273-51a64edd4b4d.svg)

**Comment by orzalaga** [comment]
![lastfm-svgrepo-com](https://user-images.githubusercontent.com/2185794/152668268-dc6c34a6-c9d8-4268-acb6-66032fd999f3.svg)

**Comment by soyjulius** [comment]
![lastfm-svgrepo-com (1)](https://user-images.githubusercontent.com/2185794/152668280-04eca6e4-8bff-4511-875f-e48ab0818a19.svg)

**Comment by orzalaga** [comment]
![bitcoin-svgrepo-com](https://user-images.githubusercontent.com/2185794/152669106-6d66252c-edc7-4c28-bae5-570a857076b0.svg)

**Comment by soyjulius** [comment]
![bitcoin-svgrepo-com (1)](https://user-images.githubusercontent.com/2185794/152669121-f6a966b8-7a83-4643-87a8-8fec8001c833.svg)

**Comment by soyjulius** [comment]
![wordpress-svgrepo-com](https://user-images.githubusercontent.com/2185794/152669143-a2dcd06c-83b0-43d0-a490-1e1cc6529d59.svg)

**Comment by orzalaga** [comment]
![Open_Source_Initiative_keyhole svg](https://user-images.githubusercontent.com/2185794/152669146-68082dd6-cb8d-4ef8-9f62-966975592a0b.png)

**Comment by soyjulius** [comment]
![apache-svgrepo-com](https://user-images.githubusercontent.com/2185794/152669202-d48d2a48-65f3-43a0-87e3-f5ca079b71fd.svg)

**Comment by soyjulius** [comment]
![ubuntu-svgrepo-com](https://user-images.githubusercontent.com/2185794/152669206-f6f42caf-d2da-4143-a321-ccac07d1f270.svg)

**Comment by soyjulius** [comment]
![cpanel-svgrepo-com](https://user-images.githubusercontent.com/2185794/152669216-599affcd-e627-4a00-8fe7-8331526d74e6.svg)

**Comment by soyjulius** [comment]
![aws-svgrepo-com](https://user-images.githubusercontent.com/2185794/152669249-8c2cb44c-568d-447f-bc5d-ebe77409601b.svg)

**Comment by soyjulius** [comment]
![crm-crm-svgrepo-com](https://user-images.githubusercontent.com/2185794/152669263-924add27-4cbe-435d-b549-505b2ecf456e.svg)

**Comment by soyjulius** [comment]
![open-source](https://user-images.githubusercontent.com/2185794/152669416-9106216d-0a3b-4d9c-9e5e-1238dc670f61.svg)

**Comment by soyjulius** [comment]
![cloud-shell-svgrepo-com](https://user-images.githubusercontent.com/2185794/152669459-f3f55906-edbe-4608-951a-4d682519706e.svg)

**Comment by soyjulius** [comment]
![linux-tux-svgrepo-com](https://user-images.githubusercontent.com/2185794/152669491-05a64a89-a849-4f28-8d0f-97368e81bec5.svg)
